name: Tests

on: 
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Install Qt
        run: sudo apt install -y qt5-default libqt5svg5-dev

      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        
      - name: Meson Build
        uses: BSFishy/meson-build@v1.0.1
        env:
          LD_LIBRARY_PATH: "$Qt5_DIR/lib"
        with:
          action: test
          directory: build
          setup-options: -Db_coverage=true
          options: --verbose


